version: '3'

services:
  contacts-api:
    build: .
    ports: 
     - 35401:5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    depends_on:
      - db
    networks:
      - contacts-api-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin123'
      POSTGRES_DB: 'intermedia-contacts'
    ports:
      - "35402:5432"
    expose:
      - "5432"
    volumes:
      - $HOME/.volumes/postgres:/var/lib/postgresql
    networks:
      - contacts-api-network

networks:
  contacts-api-network:
    driver: bridge